import { type NextPage } from 'next';
import Head from 'next/head';

import AuthShowcase from '../components/Auth';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Auth</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <AuthShowcase />
            </main>
        </>
    );
};

export default Home;
